AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs22.x
    Timeout: 10

Resources:
  # 認証つきAPI Gateweay
  MyApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Auth:
        ApiKeyRequired: true

  MySharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: "./layers/my-shared-layer"
      CompatibleRuntimes:
        - nodejs22.x
      Description: "Shared production node_modules managed by pnpm master package.json"

  GetMusicList:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/getMusicList
      FunctionName: music-stream-api-get-music-list
      Handler: index.handler
      Layers:
        - Ref: MySharedLayer
      Events:
        GetMusicListApi:
          Type: Api
          Properties:
            Path: /music
            Method: get
            RestApiId:
              Ref: MyApiGateway
  GetMusicDetail:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/getMusicDetail
      FunctionName: music-stream-api-get-music-detail
      Handler: index.handler
      Layers:
        - Ref: MySharedLayer
      Events:
        GetMusicDetailApi:
          Type: Api
          Properties:
            Path: /music/{id}
            Method: get
            RestApiId:
              Ref: MyApiGateway

Outputs:
  TargetApiId:
    Description: "API Gateway ID created by SAM"
    Value:
      Ref: ServerlessRestApi
